"use client";

import { useState } from "react";
import { LANGUAGES, DEFAULT_TARGET, type LanguageCode } from "./lib/languages";

export default function Page() {
  const [source, setSource] = useState<LanguageCode>("en-IN");
  const [target, setTarget] = useState<LanguageCode>(DEFAULT_TARGET);
  const [text, setText] = useState("Hello, how are you doing today?");
  const [out, setOut] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function translate() {
    setBusy(true);
    setErr(null);
    setOut("");
    try {
      const resp = await fetch("/api/translate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ text, source, target }),
      });
      const data = await resp.json();
      if (!resp.ok) throw new Error(data.error ?? `${resp.status}`);
      setOut(data.translated);
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <main style={styles.main}>
      <header style={styles.header}>
        <h1 style={styles.title}>Indic Translator</h1>
        <p style={styles.subtitle}>Powered by Sarvam Mayura v1</p>
      </header>

      <section style={styles.row}>
        <label style={styles.label}>
          <span>From</span>
          <select value={source} onChange={(e) => setSource(e.target.value as LanguageCode)} style={styles.select}>
            {LANGUAGES.map((l) => (
              <option key={l.code} value={l.code}>{l.name}</option>
            ))}
          </select>
        </label>
        <label style={styles.label}>
          <span>To</span>
          <select value={target} onChange={(e) => setTarget(e.target.value as LanguageCode)} style={styles.select}>
            {LANGUAGES.map((l) => (
              <option key={l.code} value={l.code}>{l.name}</option>
            ))}
          </select>
        </label>
      </section>

      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        rows={6}
        placeholder="Type or paste text…"
        style={styles.textarea}
      />

      <button onClick={translate} disabled={busy || !text.trim()} style={styles.button}>
        {busy ? "Translating…" : "Translate"}
      </button>

      {err && <p style={styles.error}>{err}</p>}
      {out && (
        <section style={styles.outBox}>
          <p style={styles.outLabel}>Translation</p>
          <p style={styles.outText}>{out}</p>
        </section>
      )}

      <footer style={styles.footer}>
        Generated by sarvam-mcp · <a href="https://docs.sarvam.ai">docs</a>
      </footer>
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  main: { maxWidth: 720, margin: "0 auto", padding: "48px 24px", fontFamily: "ui-sans-serif, system-ui, sans-serif", color: "#0a0a0b", background: "#fafafa", minHeight: "100vh" },
  header: { marginBottom: 32 },
  title: { fontSize: 36, margin: 0, fontWeight: 600, letterSpacing: "-0.02em" },
  subtitle: { color: "#737373", margin: "4px 0 0", fontSize: 14 },
  row: { display: "flex", gap: 12, marginBottom: 16 },
  label: { display: "flex", flexDirection: "column", gap: 6, flex: 1, fontSize: 13, color: "#525252" },
  select: { padding: "10px 12px", borderRadius: 8, border: "1px solid #d4d4d4", background: "white", fontSize: 14 },
  textarea: { width: "100%", padding: 16, fontSize: 16, lineHeight: 1.5, borderRadius: 12, border: "1px solid #d4d4d4", background: "white", boxSizing: "border-box", marginBottom: 12, fontFamily: "inherit", resize: "vertical" },
  button: { padding: "12px 20px", borderRadius: 10, border: "none", background: "#f97316", color: "white", fontSize: 15, fontWeight: 600, cursor: "pointer" },
  error: { color: "#dc2626", fontSize: 14, marginTop: 12 },
  outBox: { marginTop: 24, padding: 20, borderRadius: 12, background: "white", border: "1px solid #e5e5e5" },
  outLabel: { fontSize: 12, textTransform: "uppercase", letterSpacing: "0.08em", color: "#737373", margin: "0 0 8px" },
  outText: { fontSize: 18, lineHeight: 1.5, margin: 0, color: "#0a0a0b" },
  footer: { marginTop: 48, paddingTop: 24, borderTop: "1px solid #e5e5e5", fontSize: 13, color: "#a3a3a3" },
};
